service: sls-test

custom:
  settings:
    POSTS_DYNAMODB_TABLE: items

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  environment: ${self:custom.settings}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "dynamodb:GetPost"
       - "dynamodb:PutPost"
       - "dynamodb:UpdatePost"
       - "dynamodb:DeletePost"
     Resource:
      - "arm:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_DYNAMODB_TABLE}"

functions:
  savePost:
    handler: handler.savePost
    events:
      - http:
          path: post
          method: post
  getPost:
    handler: handler.getPost
    events:
      - http:
          path: post/{postId}
          method: get
  deletePost:
    handler: handler.deletePost
    events:
      - http:
          path: post/{postId}
          method: delete
  updatePost:
    handler: handler.updatePost
    events:
      - http:
          path: post/{postId}
          method: put

resources:
 Resources:
   PostsTable:
     Type: AWS::DynamoDB::Table
     Properties:
      AttributeDefinitions:
      - AttributeName: "PostId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "PostId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.settings.POSTS_DYNAMODB_TABLE}